language: go

go:
  - 1.9

services:
  - docker

install:
  - ./lint.sh

script:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - go get -t ./...
  - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo
  - export TAG=`if [ "$TRAVIS_PULL_REQUEST_BRANCH" == "" ]; then echo "latest"; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`
  - docker build -t onsdigital/go-launch-a-survey:$TAG .
  - echo "Pushing with tag [$TAG]"
  - docker push onsdigital/go-launch-a-survey:$TAG

branches:
  only:
    - master