# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: eu.gcr.io/census-eq-ci/eq-questionnaire-launcher
  tag: latest
  pullPolicy: Always

surveyRunnerUrl: ""

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
