name: Release

on:
  release:
    types: [published]

jobs:
  docker-push:
      runs-on: ubuntu-18.04
      steps:
        - uses: actions/checkout@v2
        - name: Build
          run: >
            docker build -t eu.gcr.io/${{ secrets.GCR_PROJECT_ID }}/eq-questionnaire-launcher:${{ github.event.release.tag_name }} .
        - name: Push to GCR
          env:
              GCR_SERVICE_KEY: ${{ secrets.GCR_SERVICE_KEY }}
          run: |
            echo $GCR_SERVICE_KEY | docker login -u _json_key --password-stdin https://eu.gcr.io
            echo "Pushing to GCR with tag ${{ github.event.release.tag_name }}"
            docker push eu.gcr.io/${{ secrets.GCR_PROJECT_ID }}/eq-questionnaire-launcher:${{ github.event.release.tag_name }}
